name: CI Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  backend-tests:
    name: Backend - Unit & Load Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm ci

      - name: Run unit tests (Jest)
        working-directory: ./backend
        run: npm test -- --runInBand

      - name: Run load tests (Artillery)
        working-directory: ./backend
        run: npx artillery run load-test.yml


  e2e-tests:
    name: E2E Tests (Playwright)
    runs-on: ubuntu-latest
    needs: backend-tests

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      # ---------- Backend ----------
      - name: Install backend dependencies
        working-directory: ./backend
        run: npm ci

      - name: Start backend server
        working-directory: ./backend
        run: nohup npm start &

      # ---------- Frontend ----------
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      - name: Start frontend (preview mode)
        working-directory: ./frontend
        run: nohup npm run preview &

      # ---------- Playwright ----------
      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Wait for servers
        run: |
          echo "Esperando frontend en http://localhost:4173 ..."
          npx wait-on http://localhost:4173
          echo "Esperando backend en http://localhost:3000/tasks ..."
          npx wait-on http://localhost:3000/tasks

      - name: Run E2E tests
        working-directory: ./frontend
        run: npx playwright test
